# --- Verbosity control (keep output clean) ---
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/em/verbose 0
/process/had/verbose 0
/run/particle/verbose 0
/analysis/verbose 1

# --- Initialize run (builds physics tables, geometry) ---
# Disable secondary e-
/run/setCutForAGivenParticle e- 2 m
/run/initialize
# Printing of events
/run/printProgress 10000

# --- Run the simulation ---
/run/beamOn 300000