[Gas]
Components: D2, CF4
Fractions: 95, 5
# Pressure is in mbar
Pressure: 900

[Silicons]
Specs: /media/Data/E796v2/Geant/17C/Inputs/silspecs.conf
# Specs: /media/Data/E796v2/Geant/17C/Inputs/silspecs_larger.conf
Layers: f0, f1, f2, f3, l0, r0
# Old: for s2384 setup
# Offsets: 0, 0, 0, 0, -3.36, 2.14
Offsets: 0, 0, 0, 0, 0, 0

[Beam]
# With respecto to chamber centre
# Equivalent to 110 mm wrt pad plane: -17.5 = -255./2 + 110
CentreZ: -17.5
SigmaXY: 0.5
SigmaZ: 0.5
HistEmittance: /media/Data/E796v2/Geant/17C/Inputs/emittance.root
# MeV; 15 AMeV found from Q matching
Energy: 255
# DeltaE / E = 1.25 % in sigma? according to J. C
SigmaEnergy: 4

[Kinematics]
Reaction: 17C(d,p)@255|3.44
PS: 0, 0
CrossSection: /media/Data/E796v2/Geant/17C/Inputs/dp//s.dat
