[Gas]
Components: D2, iC4H10
Fractions: 90, 10
# Pressure is in mbar
Pressure: 952

[Silicons]
Specs: /media/Data/E796v2/configs/silspecs_proposal.conf
# Specs: /media/Data/E796v2/configs/detailedSilicons.conf
Layers: f0, f1, f2, f3, l0, r0
Offsets: 0, 0, 0, 0, -3.36, 2.14

[Beam]
# With respecto to chamber centre
# Equivalent to 110 mm wrt pad plance: -17.5 = -255./2 + 110
CentreZ: -17.5
SigmaXY: 2
SigmaZ: 2
# MeV
Energy: 700.

[Kinematics]
Reaction: 20O(d,d)@700|15
PS: 0, 0
#CrossSection: /media/Data/E796v2/Fits/dt/Inputs/Daeh/gs/fort.202
CrossSection: /media/Data/E796v2/Fits/dd/Inputs/g0_Daeh/fort.201