[Gas]
Components: D2, iC4H10
Fractions: 90, 10
# Pressure is in mbar
Pressure: 950

[Silicons]
Specs: /media/Data/E796v2/configs/silspecs_proposal.conf
Layers: f0, f1, f2, f3, l0, r0
Offsets: 0, 0, 0, 0, -3.36, 2.14

[Beam]
# With respecto to chamber centre
# Equivalent to 110 mm wrt pad plance: -17.5 = -255./2 + 110
CentreZ: -17.5
SigmaXY: 2
SigmaZ: 2
# MeV; 40 AMeV found from Q matching
Energy: 640.

[Kinematics]
Reaction: 16N(d,3He)@640|0.74
PS: 0, 0
CrossSection: /media/Data/E796v2/Geant/15C/Inputs/d3He/fort.203
